### PR TITLE
Highlighter refactoring

### PR DESCRIPTION
**Pull request by bjansen**
* adds an ANTLRv4-based lexer grammar for .st files
* adds language injection to parse templates in .stg files
* replaces the custom highlighter with a more idiomatic `SyntaxHighlighterFactory`
* configures a `STLanguage` to support .st files
* reworks the structure view to use the PSI tree instead of a ParseTree

### CODE REVIEW

**Comment by Clashsoft** [comment]
> adds language injection to parse templates in .stg files

This seems like a nice addition. Here's a screenshot how it looks right now:

Screenshot 2020-06-20 at 11 26 43

There's room for improvement but I'd greatly appreciate this feature.

**Comment by bjansen** [comment]
Actually it injects the StringTemplate language in StringTemplate groups, it does *not* inject the target language (seems to be Java in your case). That would be rather pointless, because your Java code will almost never parse correctly.

Language injection does not change very much the end result, stuff will be highlighted as it was before, it's just easier to maintain in the code base.

**Comment by Clashsoft** [comment]
I understand, but what I think supporting additional highlighting in templates would be a useful feature. Of course, the language-specific parser would need to be relaxed in order to accept the ST syntax. But being able to highlight Java (or other language) keywords, comments, etc. would be cool.

**Comment by bjansen** [comment]
OK, there's a feature called "Template Data Languages" which can do this. Here's how it currently looks:

image

Note that there's no *semantic* highlighting in the Java code, i.e. annotations, class/instance members are not highlighted.

I also started adding semantic highlighting to ST tags (for example the `lexer` arg has the same color in the template definition and the template content).

**Comment by Clashsoft** [comment]
That looks very good already. Of course semantic highlighting is not possible when most of the "code" is placeholders. Looking forward to using this.

**Comment by bjansen** [comment]
I'm trying to make the template tags stand out more in this ocean of green background, what do you this of this version with chunks of white background?

image

**Comment by Clashsoft** [comment]
Yeah this looks nice. Don't forget darcula support though :) And also, this should be customizable with #21 but is a sensible default imo.

Btw, the green background comes from template data languages and can be removed via settings (Editor → Color Scheme → General → Code → Injected Language Fragment).

**Comment by bjansen** [comment]
Here's how it looks in Darcula:

image

This feels like a good visual cue to differentiate between target language and template tags.

**Pull request merged**
